# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['transcriber_app.py'],
    pathex=[],
    binaries=[],
    datas=[('C:\\Users\\35968\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\basic_pitch\\saved_models\\icassp_2022', 'basic_pitch/saved_models/icassp_2022'),
           ('C:\\Users\\35968\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\demucs\\remote', 'demucs/remote'),
           ('C:\\Users\\35968\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\mt3_infer\\config', 'mt3_infer/config')],
    hiddenimports=['demucs.pretrained', 'demucs.apply', 'demucs.htdemucs',
                   'demucs.transformer', 'demucs.repitch', 'demucs.states',
                   'demucs.spec', 'demucs.wav', 'demucs.demucs', 'demucs.hdemucs',
                   'torchaudio', 'soundfile', 'audioread', 'einops', 'julius',
                   'omegaconf', 'dora_search', 'openunmix',
                   'Crypto.Cipher.AES', 'Crypto.Cipher._mode_ecb',
                   'tkinterdnd2', 'tkinterdnd2.TkinterDnD', 'tkinterdnd2.DND_FILES',
                   'mt3_infer', 'mt3_infer.api', 'mt3_infer.base',
                   'mt3_infer.adapters', 'mt3_infer.adapters.mr_mt3',
                   'mt3_infer.adapters.mt3_pytorch', 'mt3_infer.adapters.yourmt3',
                   'mt3_infer.adapters.vocab_utils',
                   'mt3_infer.utils.download', 'mt3_infer.utils.midi',
                   'mt3_infer.models.mr_mt3', 'mt3_infer.models.mr_mt3.t5',
                   'mt3_infer.models.mt3_pytorch.t5',
                   'mt3_infer.models.mt3_pytorch.contrib.event_codec',
                   'mt3_infer.models.mt3_pytorch.contrib.note_sequences',
                   'mt3_infer.models.mt3_pytorch.contrib.spectrograms_torch',
                   'mt3_infer.models.mt3_pytorch.contrib.vocabularies',
                   'mido', 'transformers', 'huggingface_hub', 'tokenizers',
                   'safetensors', 'absl', 'absl.flags', 'tqdm',
                   'piano_transcription_inference',
                   'piano_transcription_inference.inference',
                   'piano_transcription_inference.models',
                   'piano_transcription_inference.pytorch_utils',
                   'piano_transcription_inference.utilities',
                   'piano_transcription_inference.config'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TuneScript AI V0.4',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
